src/website/__init__.py
from flask import Flask, render_template, session, request
import logging
from pymongo import MongoClient
import json
import os
from flask_babel import Babel

app = Flask(__name__)

mylogger = logging.getLogger("mylogger")
mylogger.setLevel(logging.INFO)

stream_hander = logging.StreamHandler()
mylogger.addHandler(stream_hander)


websitedir = os.path.dirname(__file__)
configfile = 'config.json'
configfile_path = os.path.join(websitedir, configfile)

with open(configfile_path, 'r') as f:
  config = json.load(f)

app.secret_key = config['app_secret_key']


client = MongoClient('mongodb://' + config['mongodb_host'] + ':' + config['mongodb_port'] + '/')
db = client[config['mongodb_name']]

babel = Babel(app)

@app.errorhandler(404)
def not_found(error):
  return render_template('404.html') ,404


@app.context_processor
def context_processor():
  return {"session":session}


@babel.localeselector
def get_locale():
  return request.accept_languages.best_match(['ko','en'])

from .views import home
from .views import auth
from .views import member
from .views import board

app.register_blueprint(home.blueprint, url_prefix='/')
app.register_blueprint(auth.blueprint, url_prefix='/auth')
app.register_blueprint(member.blueprint, url_prefix='/member')
app.register_blueprint(board.blueprint, url_prefix='/board')


from .filter import *

app.jinja_env.filters['datetime'] = format_datetime


app.config['upload_file_path'] = config['upload_file_path'] ## ex. /uploads
app.config['allow_extensions'] = set(config['allow_extensions']) ## ex. ["jpg","jpeg","png","gif"]

src/website/views/auth.py
from flask import Blueprint, render_template
from flask import request, redirect, flash, session, g
from .. import db
from datetime import datetime

blueprint = Blueprint('auth', __name__)

@blueprint.route('/signin', methods=['GET'])
def signin():
  return render_template('auth/signin.html')

@blueprint.route('/signin', methods=['POST'])
def signin_post():

  if db is not None:
    user = db.members.find_one({'userid':request.form['userid']})
    if user is None:
      error = 'invalid userid'
      flash('Invalid userid!')
      return render_template('auth/signin.html', error=error )

    elif user['password'] != request.form['passwd']:
      error = 'invalid password'
      flash('Invalid password')
      return render_template('auth/signin.html', error=error)

    else:
        session['userid'] = user['userid']
        flash('You were logged in')
        return redirect('/')  


@blueprint.route('/signup', methods=['GET'])
def signup():
  return render_template('auth/signup.html')

@blueprint.route('/signup', methods=['POST'])
def signup_post():
  if db is not None:
    user = db.members.find_one({'userid':request.form['userid']})
    if user is not None:
      error = 'already exist'
      flash('Already exist ID. Please the other ID')
      return render_template('auth/signup.html', error=error )

    member = {
      "userid" : request.form['userid'],
      "password" : request.form['passwd'],
      "created" : datetime.now()
    }

    db.members.insert(member)

    flash('Create Account')
    return redirect('/auth/signin')  

@blueprint.route('/logout')
def logout():
    session.pop('userid', None)
    flash('You were logged out')
    return redirect('/')

src/website/views/board.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from ..model.board import Board
from datetime import datetime
from werkzeug import secure_filename
import os
from .. import mylogger
import cuid
import json
import base64

blueprint = Blueprint('board', __name__)

def allowed_file(filename):
  return '.' in filename and filename.rsplit('.', 1)[1] in current_app.config['allow_extensions']


def make_dir(path):
  if os.path.exists(path) is False:
    try:
        mylogger.info('make dir : ' + path)
        original_umask = os.umask(0)
        os.makedirs(path, 0777)
    finally:
        os.umask(original_umask)

  return True


@blueprint.route('/')
def index():
  board = Board.objects.order_by('-date')
  mapper = {}
  for one in board:
    if one.attached.filename :
      with open(os.path.join(current_app.config['upload_file_path'], one.attached.filename_cuid + '.' + one.attached.file_ext)) as image_file:
        encoded_string = base64.b64encode(image_file.read())
      mapper[one.attached.filename_cuid]= encoded_string
  
  return render_template('board/list.html', collection=board, mapper=mapper)


@blueprint.route('/form', methods=['GET'])
def form():
  return render_template('/board/form.html')


@blueprint.route('/form', methods=['POST'])
def form_post():
  file = None
  if request.files:
    file = request.files['file1']
  
  attached = {}

  if file and allowed_file(file.filename):
    filename = secure_filename(file.filename)
    filename_cuid = cuid.cuid()
    file_ext = filename.rsplit('.', 1)[1]

    mylogger.info('uploaded file name : ' + filename)
    mylogger.info('uploaded file name cuid : ' + filename_cuid)
    mylogger.info('uploaded file path : ' + current_app.config['upload_file_path'])

    make_dir(current_app.config['upload_file_path'])

    file.save(os.path.join(current_app.config['upload_file_path'], filename_cuid + '.' + file_ext))

    attached['filename'] = filename
    attached['filename_cuid'] = filename_cuid
    attached['file_ext'] = file_ext


  if request.form['writer'] is not None:
    post = Board(writer=request.form['writer']
                , title=request.form['title']
                , contents=request.form['contents']
                , attached = attached
                )
    post.save()

  return redirect(url_for('board.index'))

src/website/views/home.py
from flask import Blueprint, render_template, request, redirect

blueprint = Blueprint('home', __name__)

@blueprint.route('/')
def index():
  return render_template('home/home.html')

@blueprint.route('/about/')
def about():
  return render_template('home/about.html')

src/website/views/member.py
from flask import Blueprint, render_template, request, redirect, g
from .. import db
from .. import mylogger
import json
from pymongo import ReturnDocument

blueprint = Blueprint('member', __name__)

@blueprint.route('/')
def index():
  members = db.members.find()
  
  return render_template('member/list.html', members = members)

@blueprint.route('/<userid>', methods = ['GET'])
def getMember(userid):
  member = {
    'userid': '',
    'username' : '',
  }

  try:
    ret = db.members.find_one({"userid":userid})

    member['userid'] = ret['userid']
    member['username'] = ret['username']
  except Exception as e:
    mylogger.error(e)
  
  return json.dumps(member)


@blueprint.route('/modify', methods = ['POST'])
def modifyMember():
  result = {
    'status': 'success'
  }
  try:
    ret = db.members.find_one_and_update({"userid":request.form['userid']}, 
      {'$set' : {"username":request.form['username']}
      }, return_document=ReturnDocument.AFTER)

  except Exception as e:
    mylogger.error(e)
    result['status'] = 'fail'
  
  members = db.members.find()

  return render_template('member/list.html', members = members)


@blueprint.route('/<userid>', methods = ['DELETE'])
def remove(userid):
  mylogger.info(userid + ' is deleted')

  result = {
    "status" : "success"
  }

  try:
    db.members.delete_one({"userid":userid})
  except Exception as e:
    mylogger.error(e)
    result['status'] = 'fail'

  return json.dumps(result)

src/website/templates/board/form.html
{% extends "layout.html" %}
{% block title %}
HOME
{% endblock %}
{% block link %}
{{super() }}
{% endblock %}

{% block body %}
{{ super() }}

<div class="container">
  <h1>Write something.</h1>
  <hr class="featurette-divider">
  <form action='./form' method="post" enctype="multipart/form-data">
    <div class="form-group row">
      <label for="writer" class="col-sm-2 col-form-label">Writer</label>
      <div class="col-sm-10">
        <input type="text" readonly class="form-control-plaintext" id="writer" name="writer" value="{{ session.userid if session.userid else 'anonymous'}}">
      </div>
    </div>
    <div class="form-group row">
      <label for="title" class="col-sm-2 col-form-label">Title</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="title" name="title" placeholder="Title">
      </div>
    </div>
    <div class="form-group row">
      <label for="contents" class="col-sm-2 col-form-label">Contents</label>
      <div class="col-sm-10">
        <textarea class="form-control" id="contents" rows="3" name="contents"></textarea>
      </div>
    </div>
    <!-- <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Tags</span>
          </div>
          <input type="text" class="form-control" placeholder="Tags" aria-label="Tags" aria-describedby="basic-addon1">
        </div>
      </div>
    </div> -->
    <div class="form-group row">
      <label for="contents" class="col-sm-2 col-form-label">Image</label>
      <div class="col-sm-10">
        <div class="input-group mb-3">
          <div class="custom-file">
            <input type="file" class="custom-file-input" id="file1" name="file1" aria-describedby="inputGroupFileAddon01">
            <label class="custom-file-label" for="file1">Choose file</label>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Post</button>
        <a href="/board" class="btn btn-secondary" >Back</a>
      </div>
    </div>
  </form>


</div><!-- /.container -->

{% endblock %}

src/website/templates/board/list.html
{% extends "layout.html" %}
{% block title %}
HOME
{% endblock %}
{% block link %}
{{super() }}
{% endblock %}

{% block body %}
{{ super() }}

<div class="container marketing mylist">

  <!-- START THE FEATURETTES -->
  <h1>Posts</h1>
  <hr class="featurette-divider">
  {% for board in collection %}
  <div class="row featurette">
    <div class="col-md-7">
      <span class="badge badge-info">{{board.writer}}</span>
      <h2 class="featurette-heading">{{ board.title }} <small class="text-muted">{{board.date | datetime}}</small></h2>
      <p class="lead">{{board.contents}}</p>
    </div>
    <div class="col-md-5">
      {% if board.attached.filename %}
      <img class="my-list-img featurette-image img-fluid mx-auto" src="data:image/{{board.attached.file_ext}};base64,{{mapper[board.attached.filename_cuid]}}" alt="{{ board.attached.filename }}">
      {% endif %}
    </div>
  </div>
  <hr class="featurette-divider">
  {% endfor %}

  <a href="{{url_for('board.form')}}" class="btn btn btn-outline-success btn-lg">Write</a>
</div><!-- /.container -->

{% endblock %}

src/website/templates/home/about.html
{% extends "layout.html" %}
{% block title %}
HOME
{% endblock %}
{% block link %}
{{super() }}
{% endblock %}

{% block body %}
{{ super() }}

<div class="container marketing">
  <h1>It is simple Web Site. using the next skills.</h1>
  <ul>
    <li>Docker : 17.05.0-ce</li>
    <li>Python : 2.7.12</li>
    <li>Bootstrap : 4.1.3</li>
    <li>jQuery : 3.3.1</li>
    <li>pymongo : 3.7.2</li>
    <li>Flask : 1.0.2</li>
    <li>Flask-Babel : 0.12.2</li>
    <li>Mongoengine : 0.15.3</li>
    <li>cuid : 0.3</li>
  </ul>

  <h1>What makes?</h1>
  <ul>
    <li>Simple login - just use session</li>
    <li>CRUD Member Collection</li>
    <li>Use Flask-Babel for many languages - but no messages.pot</li>
    <li>Bootstrap4 - use Start Template</li>
    <li>Board - very simple ...</li>
    <li>File upload - just image file</li>
    <li>Rendering image using base64</li>
  </ul>
</div>

{% endblock %}

src/website/templates/home/home.html
{% extends "layout.html" %}
{% block title %}
HOME
{% endblock %}
{% block link %}
{{super() }}
{% endblock %}

{% block body %}
{{ super() }}


<div class="starter-template container">
  <h1>{{ _('hello')}}
    <span class="blue">{% if session.userid %}{{session.userid}}{% endif %}</span>
  </h1>
  <p class="lead">Welcome! This is Homepage.</p>
</div>

{% endblock %}

src/website/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}LAYOUT{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
  {% block link %}{% endblock %}
</head>

<body class="bg-light">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand pl10" href="/">SIMPLE PYTHON</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
      aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse pl20p" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if nav == 'home' %}active{% endif %}">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if nav == 'about' %}active{% endif %}">
          <a class="nav-link" href="/about/">About <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if nav == 'board' %}active{% endif %}">
          <a class="nav-link" href="/board/">Board <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown {% if nav == 'admin' %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">Admin</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="/member/">Members List</a>
          </div>
        </li>
      </ul>
    </div>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        {% if session.userid %}
        <a class="nav-link" href="/auth/logout">Logout</a>
        {% else %}
        <a class="nav-link" href="/auth/signin">SignIn</a>
        {% endif %}
      </li>
    </ul>
  </nav>


  <main role="main" class="container">
    {% block body %}{% endblock %}

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="container alert {% if error %}alert-danger{% else %}alert-success{% endif %} center-block" role="alert">{{message }}</div>
    {% endfor %}
    {% else %}
    <div class="container"></div>
    {% endif %}
    {% endwith %}
  </main>

  {% block footer %}
  <script src="{{ url_for('static', filename='js/jquery.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/common.js')}}"></script>
  {% endblock %}
</body>

</html>

src/website/templates/member/list.html
{% extends "layout.html" %}
{% block title %}
HOME
{% endblock %}
{% block link %}
{{super() }}
{% endblock %}

{% block body %}
{{ super() }}

<div class="container">
  <h1>Member Manage</h1>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th class="text-center">No.</th>
          <th>ID</th>
          <th>NAME</th>
          <th>Created Date</th>
          <th class="text-center">Encrypted</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for member in members %}
        <tr>
          <td class="text-center">{{ loop.index }}</td>
          <td>{{ member.userid }}</td>
          <td>{{ member.username }}</td>
          <td>{{ member.created.strftime("%Y-%m-%d %H:%M:%S") }}</td>
          <td class="text-center">{% if member.password | length > 20 %}YES{% else %}NO{% endif %}</td>
          <td>
            <div class="float-right">
              <a href="#" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModalCenter" onclick="getMember('{{ member.userid }}')">Modify</a>
              <a href="#" class="btn btn-danger btn-sm" onclick="remove('{{ member.userid }}');">Delete</a>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Member Modify</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="modifyForm" method="POST" action="./modify">
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">User ID:</label>
            <input type="text" class="form-control" id="userid" name="userid" readonly>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Name :</label>
            <textarea class="form-control" id="username" name="username"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="modify();">Save changes</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
{{ super() }}
<script>
  function remove(userid) {
    $.ajax({
      url: `/member/${userid}`,
      method : 'delete',
      success : function(data){
        var json = JSON.parse(data);
        alert(json.status);

        $(".table > tbody > tr").each(function(){
          var tdText = $(this).find("td:eq(1)").text();
          if(userid == tdText){
            $(this).remove();
          }
        })

        $(".table > tbody > tr").each(function(idx){
          $(this).find("td:eq(0)").html(idx+1);
          idx++;
        })
      }
    })
  }

  function getMember(userid){
    $.ajax({
      url: `/member/${userid}`,
      method : 'get',
      success : function(data){
        var json = JSON.parse(data);
        $('#userid').val(json.userid);
        $('#username').val(json.username);
      }
    })
  }

  function modify(){
    modifyForm.method = 'POST';
    modifyForm.submit();
  }
</script>
{% endblock %}